name: PR Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python tests
        run: python -m unittest discover -s . -p "test_*.py"

      - name: Add second task if tests are green
        if: success()
        run: |
          mkdir task_2
          echo "# Task2 Revert git commits:- Switch Branch to fix/doom for task 2" >> task_2/README.md
