name: On Commit Testing

on:
  push:
    branches:
      - fix/commits

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Uncomment the following lines if you have dependencies to install
      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt

      - name: Run Python tests
        run: python -m unittest discover -s . -p "test_*.py"

      - name: Add second task if tests are green
        if: success()
        run: |
          mkdir -p task_3
          echo "# Task3 git rebase:- Switch Branch to fix/commits for task 3" >> task_3/README.md
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add task_3/README.md  # Corrected to task_3 from task_2
          git commit -m "Add Task 3 instructions to README"
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          git push origin HEAD:$BRANCH_NAME